// NFT Catalog - Source of Truth for Prices
const nfts = [
    {
        id: "nft-1",
        nome: "Beija-flor (R$ 1)",
        emoji: "🐦",
        image: "/beijaflor-emoji.png",
        preco: 1.00,
        raridade: "comum",
        descricao: "NFT que garante até 10 cotas. O Beija-flor-de-peito-azul simboliza beleza e agilidade.",
        cor: "from-emerald-400 to-green-500",
    },
    {
        id: "nft-2",
        nome: "Tartaruga (R$ 2)",
        emoji: "🐢",
        image: "/tartaruga-emoji.png",
        preco: 2.00,
        raridade: "comum",
        descricao: "NFT que garante até 10 cotas. A Tartaruga-de-pente vive nos mares tropicais.",
        cor: "from-blue-400 to-cyan-500",
    },
    {
        id: "nft-3",
        nome: "Garça (R$ 5)",
        emoji: "🦢",
        image: "/garca-emoji.png",
        preco: 5.00,
        raridade: "comum",
        descricao: "NFT que garante até 10 cotas. A Garça-branca-grande vive em todo o Brasil.",
        cor: "from-indigo-400 to-purple-500",
    },
    {
        id: "nft-4",
        nome: "Arara (R$ 10)",
        emoji: "🦜",
        image: "/arara-emoji.png",
        preco: 10.00,
        raridade: "raro",
        descricao: "NFT que garante até 10 cotas. A Arara-vermelha é um ícone da fauna.",
        cor: "from-red-500 to-rose-600",
    },
    {
        id: "nft-5",
        nome: "Mico-Leão (R$ 20)",
        emoji: "🐒",
        image: "/mico-emoji.png",
        preco: 20.00,
        raridade: "raro",
        descricao: "NFT que garante até 10 cotas. O Mico-leão-dourado é símbolo da conservação.",
        cor: "from-amber-400 to-orange-500",
    },
    {
        id: "nft-6",
        nome: "Onça-Pintada (R$ 50)",
        emoji: "🐆",
        image: "/onca-emoji.png",
        preco: 50.00,
        raridade: "epico",
        descricao: "NFT que garante até 10 cotas. O maior felino das Américas.",
        cor: "from-yellow-500 to-orange-600",
    },
    {
        id: "nft-7",
        nome: "Garoupa (R$ 100)",
        emoji: "🐟",
        image: "/garoupa-emoji.png",
        preco: 100.00,
        raridade: "epico",
        descricao: "NFT que garante até 10 cotas. Um peixe robusto e valioso.",
        cor: "from-cyan-500 to-blue-600",
    },
    {
        id: "nft-8",
        nome: "Lobo-Guará (R$ 200)",
        emoji: "🐺",
        image: "/lobo-emoji.png",
        preco: 200.00,
        raridade: "lendario",
        descricao: "NFT que garante até 10 cotas. O grande canídeo do Cerrado.",
        cor: "from-stone-500 to-neutral-600",
    },
    {
        id: "nft-9",
        nome: "Boto-Cor-de-Rosa (R$ 500)",
        emoji: "🐬",
        image: "/boto-emoji.png",
        preco: 500.00,
        raridade: "lendario",
        descricao: "Lenda dos rios amazônicos. Traz muita sorte em águas profundas.",
        cor: "from-pink-400 to-rose-500",
    },
    {
        id: "nft-10",
        nome: "Jacaré-Açu (R$ 1.000)",
        emoji: "🐊",
        image: "/jacare-emoji.png",
        preco: 1000.00,
        raridade: "mitico",
        descricao: "O maior predador da Amazônia. Uma força implacável e grandiosa.",
        cor: "from-emerald-600 to-green-900",
    },
    {
        id: "nft-11",
        nome: "Tucano (R$ 1.500)",
        emoji: "🦤",
        image: "/tucano-emoji.png",
        preco: 1500.00,
        raridade: "mitico",
        descricao: "Símbolo das florestas tropicais, com cores vibrantes que encantam as aves.",
        cor: "from-orange-400 to-yellow-600",
    },
    {
        id: "nft-12",
        nome: "Ararinha-Azul (R$ 2.000)",
        emoji: "🪶",
        image: "/ararinha-emoji.png",
        preco: 2000.00,
        raridade: "celestial",
        descricao: "A joia mais rara dos céus do Brasil. Beleza inestimável e proteção divina.",
        cor: "from-cyan-400 to-blue-700",
    },
];

export default nfts;
// Using ES Modules syntax since package.json likely has "type": "module" or .mjs extensions are used.
// The file server/index.js uses 'import', so this should too.
